### ISSUE TITLE
ocp-build depends on camlp4 in opam

### ISSUE THREAD

**Issue by Drup** [OCamlPro/ocp-build#13]
Is the dependency bogus ? It looks like it. Would it be possible to remove it ?

**Comment by lefessan** [comment]
No, currently, ocp-build depends on "embedded parsers" that are now only provided by camlp4. It is on our roadmap to remove the dependency, but it is still necessary for now.

**Comment by lefessan** [comment]
Fixed in 0ad9b035f843c7e2b93feaefc
