### ISSUE TITLE
[ocplib-system]  Syntax error in configuration file

### ISSUE THREAD

**Issue by cagdasbozman** [OCamlPro/ocp-build#17]
I got an error with the latest version of `ocp-build` when I try to read my [config file](https://github.com/OCamlPro/typerex-lint/blob/master/.ocplint).

```
Syntax error while parsing file .ocplint at pos 863:(Failure("ident or string expected"))
```

**Comment by lefessan** [comment]
Fixed in 0ad9b035f843c.
