### ISSUE TITLE
OCPWin64 installation deleting PATH variable 

### ISSUE THREAD

**Issue by tosanjay** [OCamlPro/ocp-build#4]
Hello,
I just installed OCPWin64 on my laptop, running windows 7. It was installed in the followinf directory (the default path and I did not change it). 
C:\Users\sanjay\AppData\Roaming\OCamlPro\OCPWin64\bin
HOwever, after the installation, I realized that some of my installed applications were not recosgnized by my CMD shell. I got suspicious and I checked my use's PATH variable to find that OCPWin64 has overwritten my PATH variable with it one entry. I lost my PATH variable which is really very annoying.
please rectify it.

**Comment by lefessan** [comment]
Definitively fixed in Jan2016 by using ocpwin.exe instead of NSIS to set the PATH.
