### ISSUE TITLE
Remove camlp4 dependency

### ISSUE THREAD

**Issue by fxfactorial** [OCamlPro/ocp-build#9]
The transitive dependency introduced by `ocp-build` is pretty big since ocp-indent depends on ocp-build and ocp-build needs camlp4 for just one file. 

With ocp-indent being used as a de facto indenter, its a little annoying to have to smuggle in camlp4 just for this one `simpleConfig.ml4`. Is it possible to rewrite `simpleConfig.ml4` without the use of camlp4? Is it there just for using `Stream`? 

Would be greatly appreciated.

**Comment by lefessan** [comment]
What's the problem with depending on `camlp4` ? 

If `camlp4` stops being maintained, we will move away, but until that, I see no reason not to use its powerful features. 

Moreover, from the `utop` discussion, `ocp-build` is not the only one to pull in `camlp4` when compiling `starterkit`, `oasis` has it as an indirect dep too, so it will not help.

**Comment by fxfactorial** [comment]
Because its a big dependency, brings in headaches for newcomers, and I thought the general direction in OCaml world was to move away from `camlp4`. Anyway, just asking, no worries if you want to ignore this/close the issue.

**Comment by lefessan** [comment]
Using `camlp4` is a headache, but installing it with `opam` brings no problem for newcomers.

FWIW, my own feeling is that `ppx` are going to suffer exactly the same problems as `camlp4` on the long term. `ppx` is a young technology, but in a few years, maintaining a `ppx` to make it work with the last 5 major releases of OCaml will be a nightmare. It might be worth comparing the two approaches in a few years.

**Comment by fxfactorial** [comment]
actually we had a few people just now have problems with camlp4, 

earlier today on IRC: 

```
<hcarty> Any idea why I would get this error from opam? "camlp4.4.02+7 is in
     conflict with lwt.2.5.1"                       [11:16]
<hcarty> There doesn't seem to be any reason why these two would be in
     conflict
<ygrek> hcarty,  "camlp4" {= "4.02+7"} (* lacks "camlp4.quotations.o" *)
<ygrek> ~/.opam/packages/lwt/lwt.2.5.1/opam
<ygrek> downgrading camlp4 works                        [11:17]
<hcarty> Ah, ok thank you!
```

and I was bit by this as well.  

Re newcomers, explaining that there are 2 ASTs, blah blah is annoying as well and needlessly confusing i think. 

Anyway, you know better than I do and I appreciate your insights and great work.

**Comment by lefessan** [comment]
Actually, I am the author of the modification to the `lwt.2.5.1` package to conflict with `camlp4.4.02+7`. I still don't know why `lwt.2.5.1` failed to compile with that version of `camlp4`, and it seems that some other users did not have such a problem. Maybe the problem is related to some depopt of `lwt`.
